### ISSUE TITLE
Automatically email stories to Premier & key cabinet personnel

### ISSUE THREAD

**Issue by kapilharesh** [my-covid-story/www#106]
As an MVP, we will first focus on...:

- [ ]  sending an email with the link to stories to premier + key cabinet personnel. Every story will trigger an email to these parties, for now (no curation)
- [ ] Once a story has been sent, add a label on the story to say we have shared to the premier/key cabinet personnel.

All stories are shared, as long as the story is published and approved. Unlike sharing with media personnel, we only share the public facing link to the premier & cabinet (which is publicly accessible anyway).

**Comment by kapilharesh** [comment]
Email template - 

**_Version - general (Premier, PM, Cabinet)_** 


Hello,

MyCovidStory.ca is a volunteer-led effort to collect and amplify the stories of those impacted by COVID-19. We believe in the power of storytelling and that because the government has refused to listen to the numbers, we want these stories to inspire evidence-based action.

The following story was submitted recently:
(Insert link)

**Every number has a story, and this is a story happening in Ontario, right now.**

We encourage you to visit www.MyCovidStory.ca to read more of these stories and to use your power to advance effective government policy that will actually save lives.

Thank you,

MyCovidStory.ca Team

**Website:** www.MyCovidStory.ca
**Twitter:** @MyCovidStory_CA

**Comment by kapilharesh** [comment]
email above is to be sent to :

1. Premier
2. ON Minister of Health
3. ON Solicitor General
4. PM JT
5. Andrea Howarth (as official ON Opposition)

Email addresses are available in the google doc, available on request. Not posted here for privacy reasons.

**Comment by davesteinberg** [comment]
Who is meant to see the label: just admins or all users? What action would they take or not take based on it? Do you envision an additional label when we start emailing to MPPs/MPs, or just a single one even then?

**Comment by kapilharesh** [comment]
@davesteinberg great question!

1.  The label will be on the public facing side, it's mainly to show users that we have indeed shared a link to the specific story to the premier / MPP. I do think we may want to put this somewhere in the form that reminds users we will share a link to the story to the premier and MPP (determined by postcode FSA). But that can be a later thing as iirc we cover this in our FAQ linked to the form. 

2. No I don't think we need unique labels for Premier and MPP, a generic "shared with govt" (?) could do the trick. Wording might need some work though. 

Hope that clarifies!

**Comment by kapilharesh** [comment]
Guessing you are working on this right now @davesteinberg so I'll assign you on this one - feel free to reassign as needed.

**Comment by davesteinberg** [comment]
A few updates after some Slack discussions to clarify some details.

- There have been some minor changes to the template. Notably, the second sentence is now, "We believe in the power of storytelling and that because the government has refused to listen to the numbers, we must make them face the stories of the people they were elected to represent."
- We wlll include the full text of the story with blockquote-style formatting, not just the link to it.
- We will recognize Ontario vs. non-Ontario stories from the postal code and choose from two lists of recipients: the one above for Ontario or PM Trudeau, Minister Freeland, and Minister Hajdu for non-Ontario. We will also tweak the subject and a couple of details for Ontario vs. non-Ontario stories.
 
Implementation is just about done. The emailing works, I just need to run it on story approval and record the message ID on the story in the database.

**Comment by davesteinberg** [comment]
One more update: We will BCC `info+mpp@mycovidstory.ca` on every email we send. That will go to our regular info email address, but it uses the [plus trick](https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html) in Gmail to allow for easy filtering. I have set up a filter that will bypass in the Inbox and apply a new label called Automatic.

This will create a permanent record of every email that has been sent automatically.
