### ISSUE TITLE
Style submission form to match designs

### ISSUE THREAD

**Issue by mwickett** [my-covid-story/www#30]
Need to adjust the Chakra theming to get us closer to design spec.

**Comment by davesteinberg** [comment]
Adjusting theming is a a bit tricky, since you can affect other stuff that's been implemented based on the defaults.

I'm resisting any temptation to change the theme until I understand it better. For now, I've just been using the style props to customize components directly to try to match the design.

Folding stuff into the theme could be a refactoring step later on?
